fix doctests
Doc-tests deskulpt_plugin

running 2 tests test crates\deskulpt-plugin\src\lib.rs -
register_commands (line 217) - compile ... FAILED test
crates\deskulpt-plugin\src\lib.rs - implement_plugin (line 102) ...
FAILED

failures:

---- crates\deskulpt-plugin\src\lib.rs - register_commands (line 217)
stdout ---- error[E0046]: not all trait items implemented, missing:
`name` --> crates\deskulpt-plugin\src\lib.rs:223:1 | 9 | impl Plugin for
MyPlugin { | ^^^^^^^^^^^^^^^^^^^^^^^^ missing `name` in implementation |
= help: implement the missing item: `fn name(&self) -> &str { todo!() }`

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0046`.
Couldn't compile the test. ---- crates\deskulpt-plugin\src\lib.rs -
implement_plugin (line 102) stdout ---- error[E0599]: no function or
associated item named `default` found for struct `MyPlugin` in the
current scope --> crates\deskulpt-plugin\src\lib.rs:114:1 | 7 | struct
MyPlugin; | --------------- function or associated item `default` not
found for this struct ... 15 | implement_plugin!(MyPlugin); |
^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in
`MyPlugin` | = help: items from traits can only be used if the trait is
implemented and in scope = note: the following trait defines an item
`default`, perhaps you need to implement it: candidate #1: `Default` =
note: this error originates in the macro `implement_plugin` (in Nightly
builds, run with -Z macro-backtrace for more info)

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.

failures: crates\deskulpt-plugin\src\lib.rs - implement_plugin (line
102) crates\deskulpt-plugin\src\lib.rs - register_commands (line 217)